eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
management:
  security:
    enabled: false
server:
  port: 8600
logging:
  file: "logs/admin-server8600.log"
spring:
  application:
    name: admin-server8600
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream