eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8500
spring:
  application:
    name: gateway-server8500
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8400
zuul:
  routes:
    api-eureka-client8200:
      path: /eureka-client-api/**
      serviceId: eureka-client