spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/tangyinbo/spring-cloud-config
         search-paths: /
         username: tangyinboit@163.com
         password: tangxuhua_520
      label: master
  application:
    name: config-server8300
server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/